//! Readers and writers for CHARMM/NAMD PSF topology files.
//!
//! PSF files are sectioned text documents.  This module models the atom and
//! bond sections needed to reconstruct a topology while deliberately ignoring
//! optional parameter sections (angles, dihedrals, and so on).  Both the
//! traditional fixed-width PSF layout and the whitespace-separated `EXT`
//! layout are accepted.

use std::fmt;
use std::fs::File;
use std::io::{self, Read, Write};
use std::path::Path;

/// An atom record from a PSF `!NATOM` section.
#[derive(Clone, Debug, PartialEq)]
pub struct PsfAtom {
    /// The atom number used by the PSF (normally one-based and contiguous).
    pub index: usize,
    /// Atom name, such as `CA`.
    pub name: String,
    /// Force-field atom type, such as `CT1` or `NH1`.
    pub atom_type: String,
    /// Residue number.
    pub resid: i32,
    /// Residue name.
    pub resname: String,
    /// Segment identifier.
    pub segid: String,
    /// Atomic mass.
    pub mass: f64,
    /// Partial charge.
    pub charge: f64,
}

impl PsfAtom {
    /// Construct an atom record with the required topology fields.
    #[must_use]
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        index: usize,
        name: impl Into<String>,
        atom_type: impl Into<String>,
        resid: i32,
        resname: impl Into<String>,
        segid: impl Into<String>,
        mass: f64,
        charge: f64,
    ) -> Self {
        Self {
            index,
            name: name.into(),
            atom_type: atom_type.into(),
            resid,
            resname: resname.into(),
            segid: segid.into(),
            mass,
            charge,
        }
    }
}

impl Default for PsfAtom {
    fn default() -> Self {
        Self::new(0, "X", "X", 1, "UNK", "SYSTEM", 0.0, 0.0)
    }
}

/// A bond from a PSF `!NBOND` section.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PsfBond {
    /// First atom number (the same one-based numbering as [`PsfAtom::index`]).
    pub atom1: usize,
    /// Second atom number.
    pub atom2: usize,
}

impl PsfBond {
    /// Construct a bond between two PSF atom numbers.
    #[must_use]
    pub const fn new(atom1: usize, atom2: usize) -> Self {
        Self { atom1, atom2 }
    }
}

/// A topology read from a CHARMM/NAMD PSF document.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct PsfStructure {
    /// Atom records in PSF order.
    pub atoms: Vec<PsfAtom>,
    /// Covalent bonds in PSF atom-number order.
    pub bonds: Vec<PsfBond>,
}

impl PsfStructure {
    /// Parse a PSF document from a string.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(input: &str) -> Result<Self, PsfError> {
        parse_psf(input)
    }

    /// Read a PSF document from any reader.
    pub fn read<R: Read>(mut reader: R) -> Result<Self, PsfError> {
        let mut input = String::new();
        reader.read_to_string(&mut input)?;
        Self::from_str(&input)
    }

    /// Read a PSF document from a filesystem path.
    pub fn read_file<P: AsRef<Path>>(path: P) -> Result<Self, PsfError> {
        Self::read(File::open(path)?)
    }

    /// Serialize this topology as a standard PSF document.
    pub fn to_psf_string(&self) -> Result<String, PsfError> {
        let mut bytes = Vec::new();
        self.write(&mut bytes)?;
        Ok(String::from_utf8_lossy(&bytes).into_owned())
    }

    /// Write this topology to any writer in standard PSF layout.
    pub fn write<W: Write>(&self, mut writer: W) -> Result<(), PsfError> {
        validate_structure(self)?;

        writeln!(writer, "PSF")?;
        writeln!(writer)?;
        writeln!(writer, "{:>8} !NTITLE", 1)?;
        writeln!(writer, "* Generated by mdanalysis-rs")?;
        writeln!(writer)?;
        writeln!(writer, "{:>8} !NATOM", self.atoms.len())?;

        for (position, atom) in self.atoms.iter().enumerate() {
            let index = if atom.index == 0 {
                position + 1
            } else {
                atom.index
            };
            writeln!(
                writer,
                "{index:>8} {:<8} {:>8} {:<8} {:>8} {:<8} {charge:>14.6} {mass:>14.6} {unused:>8}",
                atom.segid,
                atom.resid,
                atom.resname,
                atom.name,
                atom.atom_type,
                charge = atom.charge,
                mass = atom.mass,
                unused = 0,
            )?;
        }

        writeln!(writer)?;
        writeln!(writer, "{:>8} !NBOND: bonds", self.bonds.len())?;
        for (index, bond) in self.bonds.iter().enumerate() {
            if index % 4 == 0 && index != 0 {
                writeln!(writer)?;
            }
            write!(writer, "{:>8}{:>8}", bond.atom1, bond.atom2)?;
        }
        if !self.bonds.is_empty() {
            writeln!(writer)?;
        }
        Ok(())
    }

    /// Write this topology to a filesystem path.
    pub fn write_file<P: AsRef<Path>>(&self, path: P) -> Result<(), PsfError> {
        self.write(File::create(path)?)
    }
}

/// Read a PSF topology from a filesystem path.
pub fn read_psf<P: AsRef<Path>>(path: P) -> Result<PsfStructure, PsfError> {
    PsfStructure::read_file(path)
}

/// Write a PSF topology to a filesystem path.
pub fn write_psf<P: AsRef<Path>>(path: P, structure: &PsfStructure) -> Result<(), PsfError> {
    structure.write_file(path)
}

/// Errors produced while parsing or writing PSF data.
#[derive(Debug)]
pub enum PsfError {
    Io(io::Error),
    Parse { line: usize, message: String },
    InvalidStructure(String),
}

impl fmt::Display for PsfError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "I/O error: {error}"),
            Self::Parse { line, message } => {
                write!(formatter, "PSF parse error on line {line}: {message}")
            }
            Self::InvalidStructure(message) => {
                write!(formatter, "invalid PSF structure: {message}")
            }
        }
    }
}

impl std::error::Error for PsfError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}

impl From<io::Error> for PsfError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

#[derive(Clone, Copy)]
struct Section {
    count: usize,
    line: usize,
    start: usize,
    end: usize,
}

fn parse_psf(input: &str) -> Result<PsfStructure, PsfError> {
    let lines: Vec<&str> = input.lines().collect();
    let atom_section = find_section(&lines, "NATOM").ok_or_else(|| PsfError::Parse {
        line: 1,
        message: "missing !NATOM section".to_string(),
    })?;

    let mut atoms = Vec::with_capacity(atom_section.count);
    let mut records_seen = 0;
    for (offset, raw_line) in lines[atom_section.start..atom_section.end]
        .iter()
        .enumerate()
    {
        let line_number = atom_section.start + offset + 1;
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('*') {
            continue;
        }
        if records_seen >= atom_section.count {
            break;
        }
        atoms.push(parse_atom(line, line_number)?);
        records_seen += 1;
    }
    if records_seen != atom_section.count {
        return Err(PsfError::Parse {
            line: atom_section.line,
            message: format!(
                "declared {} atoms but found {records_seen}",
                atom_section.count
            ),
        });
    }

    let bond_section = find_section(&lines, "NBOND");
    let bonds = if let Some(section) = bond_section {
        parse_bonds(&lines, section)?
    } else {
        Vec::new()
    };

    let structure = PsfStructure { atoms, bonds };
    validate_structure(&structure)?;
    Ok(structure)
}

fn find_section(lines: &[&str], wanted: &str) -> Option<Section> {
    let mut sections = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        if let Some((count, marker)) = section_marker(line) {
            sections.push((index, count, marker));
        }
    }

    for (position, (index, count, marker)) in sections.iter().enumerate() {
        if marker.eq_ignore_ascii_case(wanted) {
            let end = sections
                .get(position + 1)
                .map_or(lines.len(), |next| next.0);
            return Some(Section {
                count: *count,
                line: *index + 1,
                start: *index + 1,
                end,
            });
        }
    }
    None
}

fn section_marker(line: &str) -> Option<(usize, &str)> {
    let mut tokens = line.split_whitespace();
    let count = tokens.next()?.parse::<usize>().ok()?;
    let raw_marker = tokens.next()?.strip_prefix('!')?;
    Some((
        count,
        raw_marker
            .split_once(':')
            .map_or(raw_marker, |(name, _)| name),
    ))
}

fn parse_atom(line: &str, line_number: usize) -> Result<PsfAtom, PsfError> {
    let tokens: Vec<&str> = line.split_whitespace().collect();
    if tokens.len() < 8 {
        return Err(parse_error(
            line_number,
            "NATOM record requires at least eight fields",
        ));
    }
    let index = parse_token(tokens[0], "atom index", line_number)?;
    let segid = nonempty(tokens[1], "segment id", line_number)?;
    let resid = parse_token(tokens[2], "residue id", line_number)?;
    let resname = nonempty(tokens[3], "residue name", line_number)?;
    let name = nonempty(tokens[4], "atom name", line_number)?;
    let atom_type = nonempty(tokens[5], "atom type", line_number)?;
    let charge = parse_float(tokens[6], "charge", line_number)?;
    let mass = parse_float(tokens[7], "mass", line_number)?;
    Ok(PsfAtom {
        index,
        name,
        atom_type,
        resid,
        resname,
        segid,
        mass,
        charge,
    })
}

fn parse_bonds(lines: &[&str], section: Section) -> Result<Vec<PsfBond>, PsfError> {
    let expected_values = section
        .count
        .checked_mul(2)
        .ok_or_else(|| PsfError::Parse {
            line: section.line,
            message: "bond count is too large".to_string(),
        })?;
    let mut values = Vec::with_capacity(expected_values);
    for (offset, raw_line) in lines[section.start..section.end].iter().enumerate() {
        let line_number = section.start + offset + 1;
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('*') {
            continue;
        }
        for token in line.split_whitespace() {
            if values.len() == expected_values {
                break;
            }
            values.push(parse_token(token, "bond atom index", line_number)?);
        }
        if values.len() == expected_values {
            break;
        }
    }
    if values.len() != expected_values {
        return Err(PsfError::Parse {
            line: section.line,
            message: format!(
                "declared {} bonds but found {} atom references",
                section.count,
                values.len()
            ),
        });
    }
    let mut bonds = Vec::with_capacity(values.len() / 2);
    for pair in values.chunks(2) {
        bonds.push(PsfBond::new(pair[0], pair[1]));
    }
    Ok(bonds)
}

fn validate_structure(structure: &PsfStructure) -> Result<(), PsfError> {
    use std::collections::HashSet;

    let mut indices = HashSet::with_capacity(structure.atoms.len());
    for (position, atom) in structure.atoms.iter().enumerate() {
        let effective_index = if atom.index == 0 {
            position + 1
        } else {
            atom.index
        };
        if !indices.insert(effective_index) {
            return Err(PsfError::InvalidStructure(format!(
                "duplicate atom index {}",
                effective_index
            )));
        }
        if atom.name.trim().is_empty()
            || atom.atom_type.trim().is_empty()
            || atom.resname.trim().is_empty()
            || atom.segid.trim().is_empty()
        {
            return Err(PsfError::InvalidStructure(format!(
                "atom {} has an empty topology field",
                position + 1
            )));
        }
        if atom.name.split_whitespace().count() > 1
            || atom.atom_type.split_whitespace().count() > 1
            || atom.resname.split_whitespace().count() > 1
            || atom.segid.split_whitespace().count() > 1
        {
            return Err(PsfError::InvalidStructure(format!(
                "atom {} contains whitespace in a topology field",
                position + 1
            )));
        }
        if !atom.mass.is_finite() || !atom.charge.is_finite() {
            return Err(PsfError::InvalidStructure(format!(
                "atom {} has non-finite mass or charge",
                position + 1
            )));
        }
    }

    let valid_indices: HashSet<usize> = structure
        .atoms
        .iter()
        .enumerate()
        .map(|(position, atom)| {
            if atom.index == 0 {
                position + 1
            } else {
                atom.index
            }
        })
        .collect();
    for bond in &structure.bonds {
        if !valid_indices.contains(&bond.atom1) || !valid_indices.contains(&bond.atom2) {
            return Err(PsfError::InvalidStructure(format!(
                "bond references unknown atom ({}, {})",
                bond.atom1, bond.atom2
            )));
        }
    }
    Ok(())
}

fn parse_error(line: usize, message: impl Into<String>) -> PsfError {
    PsfError::Parse {
        line,
        message: message.into(),
    }
}

fn parse_token<T>(value: &str, field: &str, line: usize) -> Result<T, PsfError>
where
    T: std::str::FromStr,
    T::Err: fmt::Display,
{
    value
        .parse::<T>()
        .map_err(|error| parse_error(line, format!("invalid {field} {value:?}: {error}")))
}

fn parse_float(value: &str, field: &str, line: usize) -> Result<f64, PsfError> {
    parse_token(&value.replace(['d', 'D'], "e"), field, line)
}

fn nonempty(value: &str, field: &str, line: usize) -> Result<String, PsfError> {
    (!value.trim().is_empty())
        .then(|| value.to_owned())
        .ok_or_else(|| parse_error(line, format!("missing {field}")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    const PSF: &str = concat!(
        "PSF\n\n",
        "       1 !NTITLE\n",
        "* test topology\n\n",
        "       3 !NATOM\n",
        "       1 SEG      1 ALA      N        NH1         -0.470000      14.007000        0\n",
        "       2 SEG      1 ALA      CA       CT1          0.070000      12.011000        0\n",
        "       3 SEG      1 ALA      C        C            0.510000      12.011000        0\n",
        "\n       2 !NBOND: bonds\n",
        "       1       2       2       3\n",
    );

    #[test]
    fn reads_charmm_psf_sections() {
        let structure = PsfStructure::from_str(PSF).expect("valid PSF");
        assert_eq!(structure.atoms.len(), 3);
        assert_eq!(structure.atoms[0].name, "N");
        assert_eq!(structure.atoms[0].atom_type, "NH1");
        assert_eq!(structure.atoms[0].resid, 1);
        assert_eq!(structure.atoms[0].resname, "ALA");
        assert_eq!(structure.atoms[0].segid, "SEG");
        assert_eq!(structure.atoms[0].mass, 14.007);
        assert_eq!(structure.atoms[0].charge, -0.47);
        assert_eq!(
            structure.bonds,
            vec![PsfBond::new(1, 2), PsfBond::new(2, 3)]
        );
    }

    #[test]
    fn writes_and_reads_back_psf() {
        let structure = PsfStructure::from_str(PSF).expect("valid PSF");
        let output = structure.to_psf_string().expect("write PSF");
        assert!(output.starts_with("PSF\n"));
        assert!(output.contains("!NATOM"));
        assert!(output.contains("!NBOND: bonds"));
        assert_eq!(
            PsfStructure::from_str(&output).expect("round trip"),
            structure
        );
    }

    #[test]
    fn supports_reader_api_and_fortran_floats() {
        let input = PSF.replace("-0.470000", "-4.700000D-01");
        let structure = PsfStructure::read(Cursor::new(input.as_bytes())).expect("read PSF");
        assert!((structure.atoms[0].charge + 0.47).abs() < 1e-12);
    }

    #[test]
    fn reports_count_and_line_for_malformed_atom() {
        let input = "PSF\n 1 !NATOM\n 1 SEG 1 ALA N NH1 bad 14.0 0\n";
        let error = PsfStructure::from_str(input).expect_err("malformed PSF");
        assert!(matches!(error, PsfError::Parse { line: 3, .. }));
    }

    #[test]
    fn rejects_bonds_outside_atom_table() {
        let input = "PSF\n 1 !NATOM\n 1 SEG 1 ALA N N 0.0 1.0 0\n 1 !NBOND: bonds\n 1 2\n";
        assert!(matches!(
            PsfStructure::from_str(input),
            Err(PsfError::InvalidStructure(_))
        ));
    }

    #[test]
    fn rejects_duplicate_effective_indices_when_writing() {
        let structure = PsfStructure {
            atoms: vec![
                PsfAtom::default(),
                PsfAtom::new(1, "CA", "CT1", 1, "ALA", "SEG", 12.0, 0.0),
            ],
            bonds: Vec::new(),
        };
        assert!(matches!(
            structure.to_psf_string(),
            Err(PsfError::InvalidStructure(_))
        ));
    }
}
